def draw_tree():
    penup()
    goto(-20, -155)
    pendown()
    fillcolor('brown')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()

    penup()
    goto(-110, -115)
    pendown()
    fillcolor('green')
    begin_fill()
    for j in range(3):
        forward(220)
        left(120)
    end_fill()

    penup()
    goto (-90,-30)
    pendown()
    fillcolor('green')
    begin_fill()
    for k in range(3):
        forward(180)
        left(120)
    end_fill()

    penup()
    goto (-70,45)
    pendown()
    fillcolor('green')
    begin_fill()
    for k in range(3):
        forward(140)
        left(120)
    end_fill()

def draw_star():
    color('yellow')
    penup()
    goto(-33,165)
    pendown()
    fillcolor('yellow')
    begin_fill()
    for p in range(10):
        forward(25)
        if p % 2 == 0:
            left(72)
        else:
            right(144)
    end_fill()

def draw_dec():
    color('black')
    penup()
    goto(-50,-80)
    pendown()
    fillcolor('red')
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(30,-5)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(0,90)
    pendown()
    begin_fill()
    circle(10)
    end_fill()

    penup()
    goto(40,-70)
    pendown()
    fillcolor('aqua')
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(-40,10)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(30,60)
    pendown()
    begin_fill()
    circle(10)
    end_fill()

    penup()
    goto(0,-90)
    pendown()
    fillcolor('white')
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(-10,-10)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(-30,70)
    pendown()
    begin_fill()
    circle(10)
    end_fill()

def draw_dec2():
    left(-90)
    penup()
    goto(-62,-30)
    pendown()
    color('yellow')
    for i in range(3):
        circle(20.5,180)
        left(-180)
    penup()
    goto(-47.5,45)
    pendown()
    for j in range(2):
        circle(23.5,180)
        left(180)
    color('')

def draw_snowman():
    color('white')
    fillcolor('white')
    penup()
    goto(-270,-105)
    pendown()
    begin_fill()
    circle(60)
    end_fill()
    penup()
    goto(-245,-15)
    pendown()
    begin_fill()
    circle(35)
    end_fill()
    
    left(135)
    color('black')
    fillcolor('brown')
    penup()
    goto(-163,-70)
    pendown()
    begin_fill()
    forward(50)
    left(90)
    forward(5)
    left(90)
    forward(50)
    left(90)
    forward(5)
    end_fill()

    left(180)
    penup()
    goto(-257,-70)
    pendown()
    begin_fill()
    forward(50)
    left(90)
    forward(5)
    left(90)
    forward(50)
    left(90)
    forward(5)
    end_fill()


    fillcolor('black')
    x = -222
    for i in range(2):
        penup()
        goto(x,-10)
        pendown()
        begin_fill()
        circle(2)
        end_fill()
        x = x + 25

    color('black')
    left(230)
    penup()
    goto(-222,-26)
    pendown()
    circle(12,180)

def draw_snow():
    color('white')
    fillcolor('white')
    penup()
    goto(-270,200)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(-200,130)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(-130,165)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(-60,230)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(10,200)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(80,150)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(150,180)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(220,90)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(290,150)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(300,80)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(-240,230)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(-230,80)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(-140,60)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(150,80)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(250,220)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(250,20)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(160,45)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    goto(300,-80)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(135,-67)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
    penup()
    goto(220,-27)
    pendown()
    begin_fill()
    circle(5.5)
    end_fill()
        

from turtle import *
bgcolor('black')
speed(0)
draw_tree()
draw_star()
draw_dec()
draw_dec2()
draw_snowman()
draw_snow()
done()